## TASK 1: Make 3 different dataframe

In [1]:
# Importing necessary libraries 
import pandas as pd
import numpy as np

# Creating Project DataFrame 
project_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005', 'A002', 'A005', 'A003', 'A001', 'A003', 'A001', 'A004', 'A004', 'A005'],
    'Project': ['Project 1', 'Project 2', 'Project 3', 'Project 4', 'Project 5', 'Project 6', 'Project 7', 'Project 8', 'Project 9', 'Project 10', 'Project 11', 'Project 12', 'Project 13', 'Project 14'],
    'Cost': [1002000, 2000000, 4500000, 5500000, np.nan, 680000, 400000, 350000, np.nan, 300000, 2000000, 1000000, 3000000, 200000],
    'Status': ['Finished', 'Ongoing', 'Finished', 'Ongoing', 'Finished', 'Failed', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Finished']
}
# Converting the project_data dictionary into a pandas DataFrame
project_dataframe = pd.DataFrame(project_data)

# Save the Project DataFrame as a CSV file 
project_dataframe.to_csv('project_data.csv', index=False)

In [2]:
# Create Employee DataFrame with employee information

employee_data = {
    'ID': ['A001', 'A002', 'A003', 'A004', 'A005'],
    'Name': ['John Alter', 'Alice Luxumberg', 'Tom Sabestine', 'Nina Adgra', 'Amy Johny'],
    'Gender': ['M', 'F', 'M', 'F', 'F'],
    'City': ['Paris', 'London', 'Berlin', 'Newyork', 'Madrid'],
    'Age': [25, 27, 29, 31, 30]
}

# Convert the employee_data dictionary into a pandas DataFrame
employee_dataframe = pd.DataFrame(employee_data)

# Save the Employee DataFrame as a CSV file
employee_dataframe.to_csv('employee_data.csv', index=False)

In [3]:
# Create Seniority Level DataFrame with employee information 

seniority_data = {
    'ID' : ['A001', 'A002', 'A003', 'A004', 'A005'],
    'Designation Level' : [2, 2, 3, 2, 3]
}

# Convert the seniority_data dictionary into a pandas DataFrame
seniority_dataframe = pd.DataFrame(seniority_data)

# Save the Seniority DataFrame as a CSV file
seniority_dataframe.to_csv('seniority_data.csv', index=False)

## Task 2 : Replace the missing values by running average

In [26]:
# Read the CSV file into a pandas DataFrame
p_dataframe = pd.read_csv('project_data.csv')

# Create an empty list to store updated cost values
updated_costs = []

# Iterate each entry in the 'Cost' column
for i in range(len(p_dataframe['Cost'])):
    
    # Get the cost value at the current index
    Cost = p_dataframe['Cost'][i]
    
    # Check if the cost coloumn has a missing value
    if pd.isna(Cost):
        
        # Calculate the mean of all previous cost values (up to index i)
        running_mean = np.mean(p_dataframe['Cost'][:i])
        
        # Append the running mean to the updated_costs list
        updated_costs.append(running_mean)
    
    # If the cost is not missing
    else:
        # Append the original cost value to the updated_costs list
        updated_costs.append(Cost)

# Replace the original 'Cost' column with the updated values
p_dataframe['Cost'] = updated_costs

# Set the display format for floating-point numbers in pandas DataFrames globally
pd.set_option('display.float_format', '{:.2f}'.format)

#Check output
p_dataframe

      ID     Project       Cost    Status
0   A001   Project 1 1002000.00  Finished
1   A002   Project 2 2000000.00   Ongoing
2   A003   Project 3 4500000.00  Finished
3   A004   Project 4 5500000.00   Ongoing
4   A005   Project 5 3250500.00  Finished
5   A002   Project 6  680000.00    Failed
6   A005   Project 7  400000.00  Finished
7   A003   Project 8  350000.00    Failed
8   A001   Project 9 2061714.29   Ongoing
9   A003  Project 10  300000.00  Finished
10  A001  Project 11 2000000.00    Failed
11  A004  Project 12 1000000.00   Ongoing
12  A004  Project 13 3000000.00  Finished
13  A005  Project 14  200000.00  Finished

## Task 3: Split the name column in the Employee dataframe into two new columns “First Name” and “Last Name” and remove the older “name” column

In [5]:
# Read the CSV File and Load Data

task_3 = pd.read_csv('employee_data.csv')
task_3

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [6]:
# Split the 'Name' Column into 'First Name' and 'Last Name'
task_3[['First Name','Last Name']] = task_3['Name'].str.split(' ',n=1, expand=True)
# Remove the Original 'Name' Column
task_3.drop('Name', axis=1, inplace=True)
# CHeck the final output
task_3

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

## Task 4 : Join all three dataframes in one single dataframe

In [7]:
# Assign the DataFrame 'p_dataframe' to a new variable called 'project_dataframe1'
project_dataframe1 = p_dataframe
# Assign the DataFrame 'task_3' (previously prepared employee data) to 'employee_dataframe1'
employee_dataframe1 = task_3
# Assign the DataFrame 'seniority_dataframe' to 'seniority_dataframe1'
seniority_dataframe1  = seniority_dataframe

In [8]:
# Merge 'project_dataframe1' and 'employee_dataframe1' using a common column 'ID'
merged1 = pd.merge(project_dataframe1,employee_dataframe1, on='ID')
# Merge the result of the previous merge ('merged1') with 'seniority_dataframe1', again using 'ID' as the key
final = pd.merge(merged1,seniority_dataframe1, on='ID')

In [9]:
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1002000.00,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2000000.00,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4500000.00,Finished,M,Berlin,29,Tom,Sabestine,3
3,A004,Project 4,5500000.00,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3250500.00,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,680000.00,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,400000.00,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,350000.00,Failed,M,Berlin,29,Tom,Sabestine,3
8,A001,Project 9,2061714.29,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,300000.00,Finished,M,Berlin,29,Tom,Sabestine,3
10,A001,Project 11,2000000.00,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1000000.00,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3000000.00,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,200000.00,Finished,F,Madrid,30,Amy,Johny,3

## Task 5: Add a new bonus column in the Final dataframe

In [10]:
# Define a function called 'bonus' that accepts a single argument 'row'
def bonus(row):
    # Check if the 'Status' column value for this row is exactly "Finished".
    if row['Status'] == "Finished":
        # If the status is "Finished", calculate 5% of the project 'Cost' as the bonus
        return row['Cost'] * 0.05
    else:
        # If the status is not "Finished" then return the string 'N.A' to indicate no bonus is assigned.
        return 'N.A'
# Apply the 'bonus' function to every row in the DataFrame 'final'
final['Bonus'] = final.apply(bonus, axis=1)

In [11]:
# Checking the final output of the 'final' dataframe
final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.00,Finished,M,Paris,25,John,Alter,2,50100.00
1,A002,Project 2,2000000.00,Ongoing,F,London,27,Alice,Luxumberg,2,N.A
2,A003,Project 3,4500000.00,Finished,M,Berlin,29,Tom,Sabestine,3,225000.00
3,A004,Project 4,5500000.00,Ongoing,F,Newyork,31,Nina,Adgra,2,N.A
4,A005,Project 5,3250500.00,Finished,F,Madrid,30,Amy,Johny,3,162525.00
5,A002,Project 6,680000.00,Failed,F,London,27,Alice,Luxumberg,2,N.A
6,A005,Project 7,400000.00,Finished,F,Madrid,30,Amy,Johny,3,20000.00
7,A003,Project 8,350000.00,Failed,M,Berlin,29,Tom,Sabestine,3,N.A
8,A001,Project 9,2061714.29,Ongoing,M,Paris,25,John,Alter,2,N.A
9,A003,Project 10,300000.00,Finished,M,Berlin,29,Tom,Sabestine,3,15000.00
10,A001,Project 11,2000000.00,Failed,M,Paris,25,John,Alter,2,N.A
11,A004,Project 12,1000000.00,Ongoing,F,Newyork,31,Nina,Adgra,2,N.A
12,A004,Project 13,3000000.00,Finished,F,Newyork,31,Nina,Adgra,2,150000.00
13,A005,Project 14,200000.00,Finished,F,Madrid,30,Amy,Johny,3,10000.00

## Task 6: Demote the designation level by 1, whose projects have status “fail”. Delete the
## employees record whose designation level is above 4.

In [12]:
# Create a new variable 'final_X' and assign the current DataFrame 'final' to it
final_X = final
# Use .loc and .isin to select rows in 'final_X' where the 'ID' is in the set of IDs with status 'Failed'
final_X.loc[final_X['ID'].isin(final[final['Status'] == 'Failed']['ID']), 'Designation Level'] += 1

In [13]:
# Filter the DataFrame 'final_X' to include only rows where the value in the 'Designation Level' column is less than or equal to 4.
# This will automatically remove those employees record whose deisgnarion level is above 4
final_X = final_X[final_X['Designation Level'] <= 4]
# Assign the updated DataFrame 'final_X' to the variable 'task6'
task6= final_X
#Check task 6 output
task6

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.00,Finished,M,Paris,25,John,Alter,3,50100.00
1,A002,Project 2,2000000.00,Ongoing,F,London,27,Alice,Luxumberg,3,N.A
2,A003,Project 3,4500000.00,Finished,M,Berlin,29,Tom,Sabestine,4,225000.00
3,A004,Project 4,5500000.00,Ongoing,F,Newyork,31,Nina,Adgra,2,N.A
4,A005,Project 5,3250500.00,Finished,F,Madrid,30,Amy,Johny,3,162525.00
5,A002,Project 6,680000.00,Failed,F,London,27,Alice,Luxumberg,3,N.A
6,A005,Project 7,400000.00,Finished,F,Madrid,30,Amy,Johny,3,20000.00
7,A003,Project 8,350000.00,Failed,M,Berlin,29,Tom,Sabestine,4,N.A
8,A001,Project 9,2061714.29,Ongoing,M,Paris,25,John,Alter,3,N.A
9,A003,Project 10,300000.00,Finished,M,Berlin,29,Tom,Sabestine,4,15000.00
10,A001,Project 11,2000000.00,Failed,M,Paris,25,John,Alter,3,N.A
11,A004,Project 12,1000000.00,Ongoing,F,Newyork,31,Nina,Adgra,2,N.A
12,A004,Project 13,3000000.00,Finished,F,Newyork,31,Nina,Adgra,2,150000.00
13,A005,Project 14,200000.00,Finished,F,Madrid,30,Amy,Johny,3,10000.00

## Task 7: Add “Mr.” and “Mrs.” to the first name column and drop the gender column.

In [14]:
 # Checkpoint
final_6 = final_X

In [15]:
# Update the 'First Name' column in the DataFrame 'final_X' with custom gender-specific prefixes
final_X['First Name'] = final_X.apply(
    # It checks the 'Gender' column of the row -
    # If the value is "M", it prefixes "Mr. " to the existing first name
    # If not (e.g., "F"), it prefixes "Mrs. " to the existing first name
    lambda row: "Mr. " + row['First Name'] if row['Gender'] == "M" else "Mrs. " + row['First Name'],
    axis=1
)

In [16]:
# Checking the final output
final_X

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.00,Finished,M,Paris,25,Mr. John,Alter,3,50100.00
1,A002,Project 2,2000000.00,Ongoing,F,London,27,Mrs. Alice,Luxumberg,3,N.A
2,A003,Project 3,4500000.00,Finished,M,Berlin,29,Mr. Tom,Sabestine,4,225000.00
3,A004,Project 4,5500000.00,Ongoing,F,Newyork,31,Mrs. Nina,Adgra,2,N.A
4,A005,Project 5,3250500.00,Finished,F,Madrid,30,Mrs. Amy,Johny,3,162525.00
5,A002,Project 6,680000.00,Failed,F,London,27,Mrs. Alice,Luxumberg,3,N.A
6,A005,Project 7,400000.00,Finished,F,Madrid,30,Mrs. Amy,Johny,3,20000.00
7,A003,Project 8,350000.00,Failed,M,Berlin,29,Mr. Tom,Sabestine,4,N.A
8,A001,Project 9,2061714.29,Ongoing,M,Paris,25,Mr. John,Alter,3,N.A
9,A003,Project 10,300000.00,Finished,M,Berlin,29,Mr. Tom,Sabestine,4,15000.00
10,A001,Project 11,2000000.00,Failed,M,Paris,25,Mr. John,Alter,3,N.A
11,A004,Project 12,1000000.00,Ongoing,F,Newyork,31,Mrs. Nina,Adgra,2,N.A
12,A004,Project 13,3000000.00,Finished,F,Newyork,31,Mrs. Nina,Adgra,2,150000.00
13,A005,Project 14,200000.00,Finished,F,Madrid,30,Mrs. Amy,Johny,3,10000.00

In [17]:
# Drop the Gender Coloumn from the final_X dataframe
final_X = final_X.drop('Gender', axis = 1)

In [18]:
#Check for output
final_X

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.00,Finished,Paris,25,Mr. John,Alter,3,50100.00
1,A002,Project 2,2000000.00,Ongoing,London,27,Mrs. Alice,Luxumberg,3,N.A
2,A003,Project 3,4500000.00,Finished,Berlin,29,Mr. Tom,Sabestine,4,225000.00
3,A004,Project 4,5500000.00,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,N.A
4,A005,Project 5,3250500.00,Finished,Madrid,30,Mrs. Amy,Johny,3,162525.00
5,A002,Project 6,680000.00,Failed,London,27,Mrs. Alice,Luxumberg,3,N.A
6,A005,Project 7,400000.00,Finished,Madrid,30,Mrs. Amy,Johny,3,20000.00
7,A003,Project 8,350000.00,Failed,Berlin,29,Mr. Tom,Sabestine,4,N.A
8,A001,Project 9,2061714.29,Ongoing,Paris,25,Mr. John,Alter,3,N.A
9,A003,Project 10,300000.00,Finished,Berlin,29,Mr. Tom,Sabestine,4,15000.00
10,A001,Project 11,2000000.00,Failed,Paris,25,Mr. John,Alter,3,N.A
11,A004,Project 12,1000000.00,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,N.A
12,A004,Project 13,3000000.00,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000.00
13,A005,Project 14,200000.00,Finished,Madrid,30,Mrs. Amy,Johny,3,10000.00

## Task 8: Promote designation level by 1 for the employees whose age is more than 29 years using IF condition

In [19]:
# Checkpoint
final_7 = final_X

In [20]:
# Update the 'Designation Level' column in the DataFrame 'final_X'
final_X['Designation Level'] = final_X.apply(
    # It checks if the 'Age' value in the current row is greater than 29 -
    # If True (employee is older than 29), adds 1 to the current 'Designation Level'
    # If False, leave the 'Designation Level' value unchanged
    lambda row: 1 + row['Designation Level'] if row['Age'] > 29 else row['Designation Level'],
    axis=1)

In [21]:
#Check output
final_X

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,Bonus
0,A001,Project 1,1002000.00,Finished,Paris,25,Mr. John,Alter,3,50100.00
1,A002,Project 2,2000000.00,Ongoing,London,27,Mrs. Alice,Luxumberg,3,N.A
2,A003,Project 3,4500000.00,Finished,Berlin,29,Mr. Tom,Sabestine,4,225000.00
3,A004,Project 4,5500000.00,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,N.A
4,A005,Project 5,3250500.00,Finished,Madrid,30,Mrs. Amy,Johny,4,162525.00
5,A002,Project 6,680000.00,Failed,London,27,Mrs. Alice,Luxumberg,3,N.A
6,A005,Project 7,400000.00,Finished,Madrid,30,Mrs. Amy,Johny,4,20000.00
7,A003,Project 8,350000.00,Failed,Berlin,29,Mr. Tom,Sabestine,4,N.A
8,A001,Project 9,2061714.29,Ongoing,Paris,25,Mr. John,Alter,3,N.A
9,A003,Project 10,300000.00,Finished,Berlin,29,Mr. Tom,Sabestine,4,15000.00
10,A001,Project 11,2000000.00,Failed,Paris,25,Mr. John,Alter,3,N.A
11,A004,Project 12,1000000.00,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,N.A
12,A004,Project 13,3000000.00,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000.00
13,A005,Project 14,200000.00,Finished,Madrid,30,Mrs. Amy,Johny,4,10000.00

## Task 9: Add the cost of all projects for each Employee and save it in new dataframe “TotalProjCost” with three columns ID, First Name, and Total cost

In [22]:
#Checkpoint
final_8 = final_X

In [23]:
# Group the DataFrame 'final_X' by the columns 'ID' and 'First Name'
# for each group, calculate the sum of the 'Cost' column (total project cost per employee)
# The resulting DataFrame 'TotalProjCost' contains columns: 'ID', 'First Name', and the summed 'Cost'
TotalProjCost = final_X.groupby(['ID', 'First Name'], as_index=False)['Cost'].sum()

In [24]:
#Check output
TotalProjCost

     ID  First Name       Cost
0  A001    Mr. John 5063714.29
1  A002  Mrs. Alice 2680000.00
2  A003     Mr. Tom 5150000.00
3  A004   Mrs. Nina 9500000.00
4  A005    Mrs. Amy 3850500.00

## Task 10: Print all the employee details whose city name contains the letter “o” in it.

In [25]:
# Filter the DataFrame 'employee_dataframe1' to include only the rows where the 'City' column contains the letter 'o'
employee_with_o = employee_dataframe1[employee_dataframe1['City'].str.contains('o')]
# Print the filtered DataFrame
print(employee_with_o)

     ID Gender     City  Age First Name  Last Name
1  A002      F   London   27      Alice  Luxumberg
3  A004      F  Newyork   31       Nina      Adgra